version: "3.8"
services:
    mongodb:
      image: mongo
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - data:/data
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      environment:
        - MONGO_INITDB_ROOT_USERNAME=userroot
        - MONGO_INITDB_ROOT_PASSWORD=pwdroot
        - MONGO_INITDB_DATABASE=incometaxbrackets
    mongo-express:
      image: mongo-express
      container_name: mongo-express
      restart: always
      ports:
        - "8081:8081"
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=userroot
        - ME_CONFIG_MONGODB_ADMINPASSWORD=pwdroot
        - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: {}
networks:
  default:
    name: mongo_network