name: Spring Boot App Test

on: 
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ secrets.ACCOUNT_NUMBER }}
        ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
      run: |
        # Build a docker container and push it to ECR 
        cd backend
        mvn clean install -DskipTests
        docker build -t psgen .
        docker tag psgen:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG:latest
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:latest"