name: Spring Boot App Test

on: 
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pre-build
        run: cd backend; ls; ./mvnw clean install -DskipTests; ls
      - name: Build Docker image
        run: docker build -t psgen .