name: Spring Boot App Test

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: ./mvnw -B package --file pom.xml
        working-directory: backend
      - name: Test with Maven
        run: ./mvnw -B test --file pom.xml
        working-directory: backend
